package taller;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan
 */
public class jose extends javax.swing.JFrame {

    String nom="";
    String ape="";
    String iden="";
    String dia="";
    String mes="";
    String mesff="";
    String diaff="";
    String pff="";
    String hff="";
    String h="";
    String niNo="";
    ArrayList<reserva> aa=new ArrayList <reserva>();
    public jose() {
        initComponents();
        jTable1.addMouseListener(new MouseAdapter(){
            DefaultTableModel m=new DefaultTableModel();
            
            public void mouseClicked(MouseEvent e){
                int i = jTable1.getSelectedRow();
                nom=(jTable1.getValueAt(i, 0).toString());
                ape=(jTable1.getValueAt(i, 1).toString());
                iden=(jTable1.getValueAt(i, 2).toString());
                dia=(jTable1.getValueAt(i, 3).toString());
                mes=(jTable1.getValueAt(i, 4).toString());
                diaff=(jTable1.getValueAt(i, 5).toString());
                mesff=(jTable1.getValueAt(i, 6).toString()); 
                pff=(jTable1.getValueAt(i, 7).toString());
                hff=(jTable1.getValueAt(i, 8).toString());        
                h=(jTable1.getValueAt(i, 9).toString());
                niNo=(jTable1.getValueAt(i, 10).toString());
            }
            
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apeliido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        identificacion = new javax.swing.JTextField();
        DiaIng = new javax.swing.JComboBox<String>();
        MesIng = new javax.swing.JComboBox<String>();
        AnoIng = new javax.swing.JComboBox<String>();
        DiaSal = new javax.swing.JComboBox<String>();
        AnoSal = new javax.swing.JComboBox<String>();
        MesSal = new javax.swing.JComboBox<String>();
        Haita = new javax.swing.JComboBox<String>();
        person = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnReserva = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        borrarlinea = new javax.swing.JButton();
        noo = new javax.swing.JTextField();
        apeeeeeee = new javax.swing.JTextField();
        ideeeeeee = new javax.swing.JTextField();
        porfin = new javax.swing.JButton();
        diaedi = new javax.swing.JTextField();
        MesEdi = new javax.swing.JTextField();
        DiaF = new javax.swing.JTextField();
        mesF = new javax.swing.JTextField();
        Hb = new javax.swing.JTextField();
        Pb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        NumHab = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        totall = new javax.swing.JLabel();
        niNo1 = new javax.swing.JLabel();
        niNos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese los siguientes datos para su reservacion:");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Fecha de ingreso");

        jLabel5.setText("Fecha de salida");

        jLabel6.setText("Habitaciones");

        jLabel7.setText("Personas");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        apeliido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apeliidoActionPerformed(evt);
            }
        });

        jLabel8.setText("Identificacion");

        identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionActionPerformed(evt);
            }
        });

        DiaIng.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DiaIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaIngActionPerformed(evt);
            }
        });

        MesIng.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic" }));

        AnoIng.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Año", "2019", "2020", "2021" }));

        DiaSal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DiaSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaSalActionPerformed(evt);
            }
        });

        AnoSal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Año", "2019", "2020", "2021" }));

        MesSal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic" }));

        Haita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        Haita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HaitaActionPerformed(evt);
            }
        });

        person.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Identificacion", "Dia de ingreso", "mes de ingreso", "Dia de salida", "mes de salida", "Habitaciones", "Personas", "Num Hab.", "niNos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnReserva.setText("Reservar");
        BtnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReservaActionPerformed(evt);
            }
        });

        BtnEditar.setText("editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        borrarlinea.setText("Borrar linea");
        borrarlinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarlineaActionPerformed(evt);
            }
        });

        noo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nooActionPerformed(evt);
            }
        });

        apeeeeeee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apeeeeeeeActionPerformed(evt);
            }
        });

        ideeeeeee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ideeeeeeeActionPerformed(evt);
            }
        });

        porfin.setText("Terminar ed.");
        porfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porfinActionPerformed(evt);
            }
        });

        diaedi.setEditable(false);
        diaedi.setText("Dia");

        MesEdi.setEditable(false);
        MesEdi.setText("Mes");

        DiaF.setEditable(false);
        DiaF.setText("Dia");

        mesF.setEditable(false);
        mesF.setText("Mes");

        Hb.setEditable(false);
        Hb.setText("Habi");

        Pb.setEditable(false);
        Pb.setText("Person");

        jLabel9.setText("Habitacion");

        NumHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumHabActionPerformed(evt);
            }
        });

        jLabel10.setText("NumHabi");

        totall.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totall.setText("Total Dia");

        niNo1.setText("niNos");

        niNos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niNosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(porfin)
                .addGap(296, 296, 296))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(borrarlinea, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEditar)
                        .addGap(192, 192, 192)
                        .addComponent(BtnSalir)
                        .addGap(63, 63, 63)
                        .addComponent(totall))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NumHab))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(DiaSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(MesSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(AnoSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(DiaIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(MesIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(AnoIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel6)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Haita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(person, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(apeliido)
                                    .addComponent(nombre))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(niNo1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(niNos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(Hb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(Pb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(diaedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MesEdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(noo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(apeeeeeee, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ideeeeeee, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(DiaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niNo1)
                    .addComponent(niNos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apeliido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DiaIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MesIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnoIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Haita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(DiaSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MesSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnoSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(person, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEditar)
                            .addComponent(BtnSalir)
                            .addComponent(borrarlinea))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totall)
                        .addGap(10, 10, 10)))
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apeeeeeee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ideeeeeee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MesEdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(porfin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReservaActionPerformed
        reserva o=new reserva(nombre.getText(),apeliido.getText(),identificacion.getText(),
                DiaIng.getSelectedItem().toString() ,DiaSal.getSelectedItem().toString(),
                person.getSelectedItem().toString(),Haita.getSelectedItem().toString(),
                MesIng.getSelectedItem().toString(),MesSal.getSelectedItem().toString(),
                NumHab.getText(), niNos.getText());
        aa.add(o);
        muestra();
        nombre.setText("");
        apeliido.setText("");
        identificacion.setText("");
        NumHab.setText("");
        niNos.setText("");
        total();
        
    }//GEN-LAST:event_BtnReservaActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        noo.setText(nom);
        apeeeeeee.setText(ape);
        ideeeeeee.setText(iden);
        diaedi.setText(dia);
        MesEdi.setText(mes);
        DiaF.setText(diaff);
        mesF.setText(mesff);
        Hb.setText(hff);
        Pb.setText(pff);
        jLabel10.setText(h);
        niNos.setText(niNo);
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void apeliidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apeliidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apeliidoActionPerformed

    private void identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionActionPerformed

    private void personActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personActionPerformed

    private void HaitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HaitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HaitaActionPerformed

    private void DiaSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaSalActionPerformed

    private void DiaIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaIngActionPerformed

    private void borrarlineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarlineaActionPerformed
        for(int i=0;i<aa.size();i++){
            if(nom==aa.get(i).getNombre()){
                aa.remove(i);
            }
        }
        String jj[][]=new String [aa.size()][10];
        
        for(int i =0;i<aa.size();i++){
            jj[i][0]=aa.get(i).getNombre();
            jj[i][1]=aa.get(i).getApellido();
            jj[i][2]=aa.get(i).getIdetificacion();
            jj[i][3]=aa.get(i).getIngreso();
            jj[i][4]=aa.get(i).getMes1();
            jj[i][5]=aa.get(i).getFin();
            jj[i][6]=aa.get(i).getMes2();
            jj[i][7]=aa.get(i).getHabi();
            jj[i][8]=aa.get(i).getPerso();
            jj[i][9]=aa.get(i).getNum();
            jj[i][10]=aa.get(i).getNiNo();
            }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            jj,
            new String [] {
                "Nombre", "Apellido", "Identificacion", "Dia de ingreso", "mes de ingreso", "Dia de salida", "mes de salida", "Habitaciones", "Personas", "Num Hab.", "niNos"
            }
        ));
    }//GEN-LAST:event_borrarlineaActionPerformed

    private void nooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nooActionPerformed

    private void apeeeeeeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apeeeeeeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apeeeeeeeActionPerformed

    private void ideeeeeeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ideeeeeeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ideeeeeeeActionPerformed

    private void porfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porfinActionPerformed
        
        for(int i=0;i<aa.size();i++){
            
            if(jLabel10.getText()==aa.get(i).getNum()){
                aa.get(i).setNombre(noo.getText());
                aa.get(i).setApellido(apeeeeeee.getText());
                aa.get(i).setIdetificacion(ideeeeeee.getText());
                aa.get(i).setIngreso(diaedi.getText());
                aa.get(i).setMes1(MesEdi.getText());
                aa.get(i).setFin(DiaF.getText());
                aa.get(i).setMes2(mesF.getText());
                aa.get(i).setHabi(Hb.getText());
                aa.get(i).setPerso(Pb.getText());
                aa.get(i).setNiNo(niNos.getText());
            }
            
            
        }
        noo.setText("");
        apeeeeeee.setText("");
        ideeeeeee.setText("");
        diaedi.setText("Dia");
        MesEdi.setText("Mes");
        DiaF.setText("Dia");
        mesF.setText("Mes");
        Hb.setText("habi");
        Pb.setText("person");
        jLabel10.setText("NumHabi");
        niNos.setText("");
        
        String jj[][]=new String [aa.size()][10];
        
        for(int i =0;i<aa.size();i++){
            jj[i][0]=aa.get(i).getNombre();
            jj[i][1]=aa.get(i).getApellido();
            jj[i][2]=aa.get(i).getIdetificacion();
            jj[i][3]=aa.get(i).getIngreso();
            jj[i][4]=aa.get(i).getMes1();
            jj[i][5]=aa.get(i).getFin();
            jj[i][6]=aa.get(i).getMes2();
            jj[i][7]=aa.get(i).getHabi();
            jj[i][8]=aa.get(i).getPerso();
            jj[i][9]=aa.get(i).getNum();
            jj[i][10]=aa.get(i).getNiNo();
            }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            jj,
            new String [] {
                "Nombre", "Apellido", "Identificacion", "Dia de ingreso", "mes de ingreso", "Dia de salida", "mes de salida", "Habitaciones", "Personas", "Num Hab.", "niNos"
            }
        ));
    }//GEN-LAST:event_porfinActionPerformed

    private void NumHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumHabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumHabActionPerformed

    private void niNosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niNosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niNosActionPerformed

    public void muestra(){
    String jj[][]=new String [aa.size()][10];
     
        for(int i =0;i<aa.size();i++){
            jj[i][0]=aa.get(i).getNombre();
            jj[i][1]=aa.get(i).getApellido();
            jj[i][2]=aa.get(i).getIdetificacion();
            jj[i][3]=aa.get(i).getIngreso();
            jj[i][4]=aa.get(i).getMes1();
            jj[i][5]=aa.get(i).getFin();
            jj[i][6]=aa.get(i).getMes2();
            jj[i][7]=aa.get(i).getHabi();
            jj[i][8]=aa.get(i).getPerso();
            jj[i][9]=aa.get(i).getNum();
            jj[i][10]=aa.get(i).getNiNo();
            }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            jj,
            new String [] {
                "Nombre", "Apellido", "Identificacion", "Dia de ingreso", "mes de ingreso", "Dia de salida", "mes de salida", "Habitaciones", "Personas", "Num Hab.", "niNos"
            }
        ));
        
    }
    public void total(){
        int total;
        
        int numero = Integer.parseInt(Haita.getSelectedItem().toString());
        
        int num = Integer.parseInt(person.getSelectedItem().toString());
        total=(numero*100)+(num*50);
        String jj="";
        jj= String.valueOf(total);
        totall.setText("$"+jj+".000");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AnoIng;
    private javax.swing.JComboBox<String> AnoSal;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnReserva;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JTextField DiaF;
    private javax.swing.JComboBox<String> DiaIng;
    private javax.swing.JComboBox<String> DiaSal;
    private javax.swing.JComboBox<String> Haita;
    private javax.swing.JTextField Hb;
    private javax.swing.JTextField MesEdi;
    private javax.swing.JComboBox<String> MesIng;
    private javax.swing.JComboBox<String> MesSal;
    private javax.swing.JTextField NumHab;
    private javax.swing.JTextField Pb;
    private javax.swing.JTextField apeeeeeee;
    private javax.swing.JTextField apeliido;
    private javax.swing.JButton borrarlinea;
    private javax.swing.JTextField diaedi;
    private javax.swing.JTextField ideeeeeee;
    private javax.swing.JTextField identificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mesF;
    private javax.swing.JLabel niNo1;
    private javax.swing.JTextField niNos;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField noo;
    private javax.swing.JComboBox<String> person;
    private javax.swing.JButton porfin;
    private javax.swing.JLabel totall;
    // End of variables declaration//GEN-END:variables
}
