package taller;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan
 */
public class jose extends javax.swing.JFrame {

    String Nombre="";
    String Apellido="";
    String Identificacion="";
    String dia="";
    String mes="";
    String mesff="";
    String diaff="";
    String pff="";
    String hff="";
    String h="";
    String niNo="";
    ArrayList<reserva> Arrayreserva=new ArrayList <reserva>();
    public jose() {
        initComponents();
        jTable1.addMouseListener(new MouseAdapter(){
            
            public void mouseClicked(MouseEvent e){
                int i = jTable1.getSelectedRow();
                Nombre=(jTable1.getValueAt(i, 0).toString());
                Apellido=(jTable1.getValueAt(i, 1).toString());
                Identificacion=(jTable1.getValueAt(i, 2).toString());
                dia=(jTable1.getValueAt(i, 3).toString());
                mes=(jTable1.getValueAt(i, 4).toString());
                diaff=(jTable1.getValueAt(i, 5).toString());
                mesff=(jTable1.getValueAt(i, 6).toString()); 
                pff=(jTable1.getValueAt(i, 7).toString());
                hff=(jTable1.getValueAt(i, 8).toString());        
                h=(jTable1.getValueAt(i, 9).toString());
                niNo=(jTable1.getValueAt(i, 10).toString());
            }
            
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LDatos = new javax.swing.JLabel();
        LNombre = new javax.swing.JLabel();
        LApellido = new javax.swing.JLabel();
        LFechaIngreso = new javax.swing.JLabel();
        LFechaSalida = new javax.swing.JLabel();
        LHabitaciones = new javax.swing.JLabel();
        LPersonas = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apeliido = new javax.swing.JTextField();
        LIdentificacion = new javax.swing.JLabel();
        identificacion = new javax.swing.JTextField();
        DiaIngreso = new javax.swing.JComboBox<String>();
        MesIngreso = new javax.swing.JComboBox<String>();
        AnoIngreso = new javax.swing.JComboBox<String>();
        DiaSalida = new javax.swing.JComboBox<String>();
        AnoSalida  = new javax.swing.JComboBox<String>();
        MesSalida = new javax.swing.JComboBox<String>();
        Haita = new javax.swing.JComboBox<String>();
        person = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnReserva = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        borrarlinea = new javax.swing.JButton();
        noo = new javax.swing.JTextField();
        apeeeeeee = new javax.swing.JTextField();
        ideeeeeee = new javax.swing.JTextField();
        porfin = new javax.swing.JButton();
        diaedi = new javax.swing.JTextField();
        MesEdi = new javax.swing.JTextField();
        DiaFin = new javax.swing.JTextField();
        mesFin = new javax.swing.JTextField();
        Hb = new javax.swing.JTextField();
        Pb = new javax.swing.JTextField();
        LHabitacionEditar = new javax.swing.JLabel();
        NumeroHabitacion = new javax.swing.JTextField();
        LNumeroHabitacion = new javax.swing.JLabel();
        totall = new javax.swing.JLabel();
        niNo1 = new javax.swing.JLabel();
        niNos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        LDatos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LDatos.setText("Ingrese los siguientes datos para su reservacion:");

        LNombre.setText("Nombre");

        LApellido.setText("Apellido");

        LFechaIngreso.setText("Fecha de ingreso");

        LFechaSalida.setText("Fecha de salida");

        LHabitaciones.setText("Habitaciones");

        LPersonas.setText("Personas");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        apeliido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apeliidoActionPerformed(evt);
            }
        });

        LIdentificacion.setText("Identificacion");

        identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionActionPerformed(evt);
            }
        });

        DiaIngreso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DiaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaIngActionPerformed(evt);
            }
        });

        MesIngreso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic" }));

        AnoIngreso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Año", "2019", "2020", "2021" }));

        DiaSalida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DiaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaSalActionPerformed(evt);
            }
        });

        AnoSalida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Año", "2019", "2020", "2021" }));

        MesSalida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic" }));

        Haita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        Haita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HaitaActionPerformed(evt);
            }
        });

        person.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Identificacion", "Dia de ingreso", "mes de ingreso", "Dia de salida", "mes de salida", "Habitaciones", "Personas", "Num Hab.", "niNos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnReserva.setText("Reservar");
        BtnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReservaActionPerformed(evt);
            }
        });

        BtnEditar.setText("editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        borrarlinea.setText("Borrar linea");
        borrarlinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarlineaActionPerformed(evt);
            }
        });

        noo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nooActionPerformed(evt);
            }
        });

        apeeeeeee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apeeeeeeeActionPerformed(evt);
            }
        });

        ideeeeeee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ideeeeeeeActionPerformed(evt);
            }
        });

        porfin.setText("Terminar ed.");
        porfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porfinActionPerformed(evt);
            }
        });

        diaedi.setEditable(false);
        diaedi.setText("Dia");

        MesEdi.setEditable(false);
        MesEdi.setText("Mes");

        DiaFin.setEditable(false);
        DiaFin.setText("Dia");

        mesFin.setEditable(false);
        mesFin.setText("Mes");

        Hb.setEditable(false);
        Hb.setText("Habi");

        Pb.setEditable(false);
        Pb.setText("Person");

        LHabitacionEditar.setText("Habitacion");

        NumeroHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumHabActionPerformed(evt);
            }
        });

        LNumeroHabitacion.setText("NumHabi");

        totall.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totall.setText("Total Dia");

        niNo1.setText("niNos");

        niNos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niNosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(porfin)
                .addGap(296, 296, 296))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(borrarlinea, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEditar)
                        .addGap(192, 192, 192)
                        .addComponent(BtnSalir)
                        .addGap(63, 63, 63)
                        .addComponent(totall))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LNombre)
                                    .addComponent(LFechaIngreso)
                                    .addComponent(LApellido)
                                    .addComponent(LIdentificacion)
                                    .addComponent(LFechaSalida))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LHabitacionEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NumeroHabitacion))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(DiaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(MesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(AnoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LPersonas))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(DiaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(MesIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(AnoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(LHabitaciones)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Haita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(person, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(apeliido)
                                    .addComponent(nombre))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(niNo1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(niNos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(Hb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(Pb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNumeroHabitacion)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(diaedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MesEdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(noo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(apeeeeeee, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ideeeeeee, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(DiaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niNo1)
                    .addComponent(niNos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LApellido)
                    .addComponent(apeliido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LIdentificacion)
                    .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LHabitacionEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LFechaIngreso)
                    .addComponent(DiaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MesIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Haita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPersonas)
                    .addComponent(DiaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LFechaSalida)
                    .addComponent(person, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEditar)
                            .addComponent(BtnSalir)
                            .addComponent(borrarlinea))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totall)
                        .addGap(10, 10, 10)))
                .addComponent(LNumeroHabitacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apeeeeeee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ideeeeeee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MesEdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(porfin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReservaActionPerformed
        reserva o=new reserva(nombre.getText(),apeliido.getText(),identificacion.getText(),
                DiaIngreso.getSelectedItem().toString() ,DiaSalida.getSelectedItem().toString(),
                person.getSelectedItem().toString(),Haita.getSelectedItem().toString(),
                MesIngreso.getSelectedItem().toString(),MesSalida.getSelectedItem().toString(),
                NumeroHabitacion.getText(), niNos.getText());
        Arrayreserva.add(o);
        muestra();
        nombre.setText("");
        apeliido.setText("");
        identificacion.setText("");
        NumeroHabitacion.setText("");
        niNos.setText("");
        total();
        
    }//GEN-LAST:event_BtnReservaActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        noo.setText(Nombre);
        apeeeeeee.setText(Apellido);
        ideeeeeee.setText(Identificacion);
        diaedi.setText(dia);
        MesEdi.setText(mes);
        DiaFin.setText(diaff);
        mesFin.setText(mesff);
        Hb.setText(hff);
        Pb.setText(pff);
        LNumeroHabitacion.setText(h);
        niNos.setText(niNo);
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void apeliidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apeliidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apeliidoActionPerformed

    private void identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionActionPerformed

    private void personActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personActionPerformed

    private void HaitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HaitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HaitaActionPerformed

    private void DiaSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaSalActionPerformed

    private void DiaIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaIngActionPerformed

    private void borrarlineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarlineaActionPerformed
        for(int i=0;i<Arrayreserva.size();i++){
            if(Nombre==Arrayreserva.get(i).getNombre()){
                Arrayreserva.remove(i);
            }
        }
        String matriz[][]=new String [Arrayreserva.size()][10];
        
        for(int i =0;i<Arrayreserva.size();i++){
            matriz[i][0]=Arrayreserva.get(i).getNombre();
            matriz[i][1]=Arrayreserva.get(i).getApellido();
            matriz[i][2]=Arrayreserva.get(i).getIdetificacion();
            matriz[i][3]=Arrayreserva.get(i).getIngreso();
            matriz[i][4]=Arrayreserva.get(i).getMes1();
            matriz[i][5]=Arrayreserva.get(i).getFin();
            matriz[i][6]=Arrayreserva.get(i).getMes2();
            matriz[i][7]=Arrayreserva.get(i).getHabi();
            matriz[i][8]=Arrayreserva.get(i).getPerso();
            matriz[i][9]=Arrayreserva.get(i).getNum();
            matriz[i][10]=Arrayreserva.get(i).getNiNo();
            }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Nombre", "Apellido", "Identificacion", "Dia de ingreso", "mes de ingreso", "Dia de salida", "mes de salida", "Habitaciones", "Personas", "Num Hab.", "niNos"
            }
        ));
    }//GEN-LAST:event_borrarlineaActionPerformed

    private void nooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nooActionPerformed

    private void apeeeeeeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apeeeeeeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apeeeeeeeActionPerformed

    private void ideeeeeeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ideeeeeeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ideeeeeeeActionPerformed

    private void porfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porfinActionPerformed
        
        for(int i=0;i<Arrayreserva.size();i++){
            
            if(LNumeroHabitacion.getText()==Arrayreserva.get(i).getNum()){
                Arrayreserva.get(i).setNombre(noo.getText());
                Arrayreserva.get(i).setApellido(apeeeeeee.getText());
                Arrayreserva.get(i).setIdetificacion(ideeeeeee.getText());
                Arrayreserva.get(i).setIngreso(diaedi.getText());
                Arrayreserva.get(i).setMes1(MesEdi.getText());
                Arrayreserva.get(i).setFin(DiaFin.getText());
                Arrayreserva.get(i).setMes2(mesFin.getText());
                Arrayreserva.get(i).setHabi(Hb.getText());
                Arrayreserva.get(i).setPerso(Pb.getText());
                Arrayreserva.get(i).setNiNo(niNos.getText());
            }
            
            
        }
        noo.setText("");
        apeeeeeee.setText("");
        ideeeeeee.setText("");
        diaedi.setText("Dia");
        MesEdi.setText("Mes");
        DiaFin.setText("Dia");
        mesFin.setText("Mes");
        Hb.setText("habi");
        Pb.setText("person");
        LNumeroHabitacion.setText("NumHabi");
        niNos.setText("");
        
        String matriz[][]=new String [Arrayreserva.size()][10];
        
        for(int i =0;i<Arrayreserva.size();i++){
            matriz[i][0]=Arrayreserva.get(i).getNombre();
            matriz[i][1]=Arrayreserva.get(i).getApellido();
            matriz[i][2]=Arrayreserva.get(i).getIdetificacion();
            matriz[i][3]=Arrayreserva.get(i).getIngreso();
            matriz[i][4]=Arrayreserva.get(i).getMes1();
            matriz[i][5]=Arrayreserva.get(i).getFin();
            matriz[i][6]=Arrayreserva.get(i).getMes2();
            matriz[i][7]=Arrayreserva.get(i).getHabi();
            matriz[i][8]=Arrayreserva.get(i).getPerso();
            matriz[i][9]=Arrayreserva.get(i).getNum();
            matriz[i][10]=Arrayreserva.get(i).getNiNo();
            }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Nombre", "Apellido", "Identificacion", "Dia de ingreso", "mes de ingreso", "Dia de salida", "mes de salida", "Habitaciones", "Personas", "Num Hab.", "niNos"
            }
        ));
    }//GEN-LAST:event_porfinActionPerformed

    private void NumHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumHabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumHabActionPerformed

    private void niNosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niNosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niNosActionPerformed

    public void muestra(){
    String matriz[][]=new String [Arrayreserva.size()][10];
     
        for(int i =0;i<Arrayreserva.size();i++){
            matriz[i][0]=Arrayreserva.get(i).getNombre();
            matriz[i][1]=Arrayreserva.get(i).getApellido();
            matriz[i][2]=Arrayreserva.get(i).getIdetificacion();
            matriz[i][3]=Arrayreserva.get(i).getIngreso();
            matriz[i][4]=Arrayreserva.get(i).getMes1();
            matriz[i][5]=Arrayreserva.get(i).getFin();
            matriz[i][6]=Arrayreserva.get(i).getMes2();
            matriz[i][7]=Arrayreserva.get(i).getHabi();
            matriz[i][8]=Arrayreserva.get(i).getPerso();
            matriz[i][9]=Arrayreserva.get(i).getNum();
            matriz[i][10]=Arrayreserva.get(i).getNiNo();
            }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Nombre", "Apellido", "Identificacion", "Dia de ingreso", "mes de ingreso", "Dia de salida", "mes de salida", "Habitaciones", "Personas", "Num Hab.", "niNos"
            }
        ));
        
    }
    public void total(){
        int total;
        
        int numero = Integer.parseInt(Haita.getSelectedItem().toString());
        
        int num = Integer.parseInt(person.getSelectedItem().toString());
        total=(numero*100)+(num*50);
        String jj=" ";
        jj= String.valueOf(total);
        totall.setText("$"+jj+".000");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AnoIngreso;
    private javax.swing.JComboBox<String> AnoSalida;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnReserva;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JTextField DiaFin;
    private javax.swing.JComboBox<String> DiaIngreso;
    private javax.swing.JComboBox<String> DiaSalida;
    private javax.swing.JComboBox<String> Haita;
    private javax.swing.JTextField Hb;
    private javax.swing.JTextField MesEdi;
    private javax.swing.JComboBox<String> MesIngreso;
    private javax.swing.JComboBox<String> MesSalida;
    private javax.swing.JTextField NumeroHabitacion;
    private javax.swing.JTextField Pb;
    private javax.swing.JTextField apeeeeeee;
    private javax.swing.JTextField apeliido;
    private javax.swing.JButton borrarlinea;
    private javax.swing.JTextField diaedi;
    private javax.swing.JTextField ideeeeeee;
    private javax.swing.JTextField identificacion;
    private javax.swing.JLabel LDatos;
    private javax.swing.JLabel LNumeroHabitacion;
    private javax.swing.JLabel LNombre;
    private javax.swing.JLabel LApellido;
    private javax.swing.JLabel LFechaIngreso;
    private javax.swing.JLabel LFechaSalida;
    private javax.swing.JLabel LHabitaciones;
    private javax.swing.JLabel LPersonas;
    private javax.swing.JLabel LIdentificacion;
    private javax.swing.JLabel LHabitacionEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mesFin;
    private javax.swing.JLabel niNo1;
    private javax.swing.JTextField niNos;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField noo;
    private javax.swing.JComboBox<String> person;
    private javax.swing.JButton porfin;
    private javax.swing.JLabel totall;
    // End of variables declaration//GEN-END:variables
}
